# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
import hashlib
import math
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadRequest
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported
from ccxt.base.decimal_to_precision import TICK_SIZE


class youngplatform(Exchange):

    def describe(self):
        return self.deep_extend(super(youngplatform, self).describe(), {
            'id': 'youngplatform',
            'name': 'YoungPlatform',
            'countries': ['IT'],
            'rateLimit': 2000,
            'certified': False,
            'pro': False,
            # new metainfo interface
            'has': {
                'fetchClosedOrders': True,
                'fetchOHLCV': True,
                'fetchTrades': True,
                'fetchTime': 'emulated',  # TODO
                'fetchOrderBook': True,
                'fetchMarkets': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchBalance': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchCurrencies': True,
                'fetchMyTrades': True,
                'createOrder': True,
                'createMarketOrder': True,
                'cancelOrder': True,
                'cancelAllOrders': True,
                'fetchDepositAddress': True,
                'withdraw': True,
            },
            'timeframes': {
                '1m': 1,
                '5m': 5,
                '15m': 15,
                '1h': 60,
                '4h': 240,
                '1d': 1440,
                '1w': 10080,
                '1M': 43200,
            },
            'urls': {
                'logo': 'https://exchange.youngplatform.com/61be7df7438ee83abe1fd2e37c7b71bf.svg',
                'test': {
                    'public': 'https://testnode.youngplatform.com',
                    'private': 'https://testnode.youngplatform.com/order/v2',
                },
                'api': {
                    'public': 'https://node1.youngplatform.com',
                    'private': 'https://node1.youngplatform.com/order/v2',
                },
                'www': 'https://pro.youngplatform.com',
                'doc': [],
                'fees': 'https://pro.youngplatform.com/fees',
            },
            'api': {
                'public': {
                    'get': [
                        'market/get-market-summary/{pair}',
                        'api/GetSettings',
                        'api/CurrencySettings',
                        'cmc/v1/orderbook/{pair}/{limit}',
                        'market/get-trade-history/{pair}',
                        'market/get-chart-data',
                    ],
                    'put': [],
                    'post': [],
                    'delete': [],
                },
                'private': {
                    'get': [],
                    'post': [
                        'get-balance',
                        'PlaceOrder',
                        'cancel-my-order',
                        'cancel-all-my-orders',
                        'GenerateAddress',
                        'my-order-history',
                        'my-order-status',
                        'my-trade-history',
                    ],
                    'delete': [],
                },
            },
            'precisionMode': TICK_SIZE,
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'taker': 0.2,
                    'maker': 0.2,
                },
            },
            'commonCurrencies': {
                'MCDAI': 'DAI',
            },
            # exchange-specific options
            'options': {
                # 'fetchTradesMethod': 'publicGetAggTrades',  # publicGetTrades, publicGetHistoricalTrades
                'defaultTimeInForce': 'GTC',  # 'GTC' = Good To Cancel(default), 'IOC' = Immediate Or Cancel
                'recvWindow': 5 * 1000,  # 5 sec
                'timeDifference': 0,  # the difference between system clock and Binance clock
                'adjustForTimeDifference': False,  # controls the adjustment logic upon instantiation
            },
            # https://binance-docs.github.io/apidocs/spot/en/#error-codes-2
            'exceptions': {},
        })

    def nonce(self):
        return self.milliseconds() - self.options['timeDifference']

    async def fetch_time(self, params={}):
        return self.milliseconds()

    async def load_time_difference(self, params={}):
        serverTime = await self.fetch_time(params)
        after = self.milliseconds()
        self.options['timeDifference'] = after - serverTime
        return self.options['timeDifference']

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        if not (api in self.urls['api']):
            raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
        request = '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        if method == 'GET':
            if query:
                request += '?' + self.urlencode(query)
        if api == 'private':
            if params['limit'] is not None:
                request += '?' + self.urlencode({'limit': params['limit'], 'page': params['page']})
                del params['limit']
                del params['page']
            self.check_required_credentials()
            nonce = int(self.nonce() / 1000)
            params = self.extend({'timestamp': nonce, 'recvWindow': 5000}, params)
            hmac = self.get_hmac_from_object(params)
            body = self.json(params)
            headers = {
                'apiKey': self.apiKey,
                'HMAC': hmac,
                'Content-Type': 'application/json',
            }
        url = self.urls['api'][api] + request
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    async def fetch_balance(self, params={}):
        currency = self.safe_string(params, 'currency')
        if currency is None:
            currency = 'ALL'
        else:
            currency = self.currency_id(currency)
        params['currency'] = currency
        response = await self.privatePostGetBalance(params)
        balances = self.safe_value(response, 'data', {})
        result = {'info': balances}
        for i in range(0, len(balances)):
            currencyId = self.safe_string(balances[i], 'currency')
            code = self.safe_currency_code(currencyId)
            account = self.account()
            free = self.safe_float(balances[i], 'balance')
            used = self.safe_float(balances[i], 'balanceInTrade')
            total = free + used
            account['total'] = total
            account['free'] = free
            account['used'] = used
            result[code] = account
        return self.parse_balance(result)

    async def create_order(self, symbol, type, side, amount, price=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        exchangeType = type.upper()
        exchangeSide = side.upper()
        baseId = market['id'].split('_')[1]
        quoteId = market['id'].split('_')[0]
        request = {
            'market': quoteId,
            'trade': baseId,
            'side': exchangeSide,
            'type': exchangeType,  # MARKET, LIMIT, STOPLIMIT
            'volume': self.amount_to_precision(symbol, amount),
        }
        if exchangeType == 'LIMIT':
            if price is None:
                raise InvalidOrder(self.id + ' createOrder method requires a price argument for a ' + type + ' order')
            request['rate'] = self.price_to_precision(symbol, price)
            timeInForce = self.safe_string(params, 'timeInForce')
            if timeInForce is not None:
                if timeInForce != 'GTC' and timeInForce != 'IOC' and timeInForce != 'FOK':
                    request['timeInForce'] = timeInForce
        if exchangeType == 'STOPLIMIT':
            stopPrice = self.safe_float(params, 'stopPrice')
            if price is None:
                raise InvalidOrder(self.id + ' createOrder method requires a price argument for a ' + type + ' order')
            if stopPrice is None:
                raise InvalidOrder(self.id + ' createOrder method requires a stop argument for a ' + type + ' order')
            request['rate'] = self.price_to_precision(symbol, price)
            request['stop'] = self.price_to_precision(symbol, stopPrice)
        if exchangeType == 'STOPMARKET':
            stopPrice = self.safe_float(params, 'stopPrice')
            if stopPrice is None:
                raise InvalidOrder(self.id + ' createOrder method requires a stop argument for a ' + type + ' order')
            request['stop'] = self.price_to_precision(symbol, stopPrice)
            request['timeInForce'] = 'GTC'
        if exchangeType == 'MARKET':
            if price is not None:
                raise InvalidOrder(self.id + ' createOrder method does not support price argument for a ' + type + ' order')
        response = await self.privatePostPlaceOrder(request)
        #
        #     {
        #         status: 'Success',
        #         data: {
        #             "orderId": 214083724
        #         }
        #    }
        #
        timestamp = self.seconds()
        result = self.safe_value(response, 'data')
        id = self.safe_integer(result, 'orderId')
        order = {
            'id': id,
            'info': response,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': type,
            'side': side,
            'price': price,
            'amount': amount,
            'cost': None,
            'average': None,
            'filled': None,
            'remaining': None,
            'status': None,
            'fee': None,
            'trades': None,
        }
        return order

    async def cancel_order(self, id, symbol=None, params={}):
        await self.load_markets()
        response = None
        response = await self.privatePostCancelMyOrder(self.extend({
            'orderId': int(id),
            'side': 'ALL',
        }, params))
        data = self.safe_value(response, 'data')
        if data == 'Order not found.':
            raise OrderNotFound(self.id + ' cancelOrder() error order not found')
        return response

    async def cancel_all_orders(self, symbol=None, params={}):
        if symbol is None:
            raise ArgumentsRequired(self.id + ' cancelAllOrders requires a symbol argument')
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
            'side': 'ALL',
        }
        response = await self.privatePostCancelAllMyOrders(request)
        return response

    async def fetch_deposit_address(self, code, params={}):
        await self.load_markets()
        currencies = await self.fetch_currencies()
        currency = self.safe_value(currencies, code)
        if currency is None:
            raise BadRequest(self.id + ' fetchDepositAddress() error invalid currency')
        request = {
            'currency': currency['id'],
        }
        separator = currency['info']['addressSeparator'].lower()
        response = await self.privatePostGenerateAddress(request)  # overwrite methods
        result = response['data']
        address = self.safe_string(result, 'Address')
        tag = ''
        if separator is not None and separator != '':
            s = address.lower().split(separator)
            tag = s[1]
            address = address.substr(
                0,
                len(s[0])
            )
        self.check_address(address)
        return {
            'currency': code,
            'address': address,
            'tag': tag,
            'info': response,
        }

    async def fetch_open_orders(self, symbol=None, since=None, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'side': 'ALL',
            'pair': market['id'],
            'openOrders': True,
        }
        if limit is not None:
            request['limit'] = limit
        else:
            request['limit'] = 20
        if params['page'] is not None:
            request['page'] = params['page']
        else:
            request['page'] = 1
        response = await self.privatePostMyOrderHistory(request)
        data = self.safe_value(response, 'data')
        orders = self.safe_value(data, 'orders')
        return self.parse_orders(orders, market, since, limit)

    async def fetch_closed_orders(self, symbol=None, since=None, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'side': 'ALL',
            'pair': market['id'],
            'openOrders': False,
            'limit': 20,
            'page': 1,
        }
        if limit is not None:
            request['limit'] = limit
        if params['page'] is not None:
            request['page'] = params['page']
        response = await self.privatePostMyOrderHistory(request)
        data = self.safe_value(response, 'data')
        orders = self.safe_value(data, 'orders')
        return self.parse_orders(orders, market, since, limit)

    async def fetch_order(self, id, symbol=None, params={}):
        await self.load_markets()
        request = {
            'side': 'ALL',
            'OrderId': id,
        }
        response = await self.privatePostMyOrderStatus(request)
        order = self.safe_value(response, 'data')
        return self.parse_order(self.normalize_order_object(order))

    async def fetch_markets(self, params={}):
        response = await self.publicGetApiGetSettings()
        if self.options['adjustForTimeDifference']:
            await self.load_time_difference()
        data = self.safe_value(response, 'data')
        res = self.safe_value(data, 'trade_setting')
        result = []
        for i in range(0, len(res)):
            market = res[i]
            baseId = self.safe_string(market, 'coinName')
            quoteId = self.safe_string(market, 'marketName')
            id = quoteId + '_' + baseId
            base = self.safe_currency_code(baseId)
            quote = self.safe_currency_code(quoteId)
            symbol = base + '/' + quote
            active = self.safe_value(market, 'tradeEnabled')
            taker = self.safe_float(market, 'takerFee')
            maker = self.safe_float(market, 'makerFee')
            lotSize = self.safe_float(market, 'minTradeAmount')
            tickSize = self.safe_float(market, 'minTickSize')
            minCost = self.safe_float(market, 'minOrderValue')
            # TODO: precision
            result.append({
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'active': active,
                'precision': {
                    'amount': lotSize,
                    'price': tickSize,
                },
                'taker': taker,
                'maker': maker,
                'limits': {
                    'amount': {
                        'min': None,
                        'max': None,
                    },
                    'price': {
                        'min': None,
                        'max': None,
                    },
                    'cost': {
                        'min': minCost,
                        'max': None,
                    },
                },
                'info': market,
            })
        return result

    async def fetch_ticker(self, symbol, params={}):
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
        }
        response = await self.publicGetMarketGetMarketSummaryPair(request)
        ticker = self.safe_value(response, 'data')
        return self.parse_ticker(ticker, market['id'])

    async def fetch_tickers(self, symbol=None, params={}):
        await self.load_markets()
        request = {
            'pair': '',  # force fetch all tickers
        }
        response = await self.publicGetMarketGetMarketSummaryPair(request)
        tickers = self.safe_value(response, 'data')
        return self.parse_tickers(tickers)

    async def fetch_currencies(self, params={}):
        response = await self.publicGetApiCurrencySettings(params)
        currencies = self.safe_value(response, 'data')
        result = {}
        for i in range(0, len(currencies)):
            id = self.safe_string(currencies[i], 'shortName')
            # fees can have both percentage and flat fee
            code = self.safe_currency_code(id)
            name = self.safe_string(currencies[i], 'fullName')
            decimal = self.safe_integer(currencies[i], 'decimalPrecision')
            precision = math.pow(10, -decimal)
            # is active only if all of the below are True
            buyEnabled = self.safe_value(currencies[i], 'tradeEnabled_Buy')
            sellEnabled = self.safe_value(currencies[i], 'tradeEnabled_Sell')
            depositEnabled = self.safe_value(currencies[i], 'depositEnabled')
            withdrawalEnabled = self.safe_value(currencies[i], 'withdrawalEnabled')
            feeType = self.safe_string(currencies[i], 'withdrawalServiceChargeType')
            flatFee = self.safe_float(currencies[i], 'withdrawalServiceCharge')
            feePercentage = self.safe_float(currencies[i], 'withdrawalServiceChargeInBTC')
            if feeType == 'Percentage':
                if feePercentage == 0:
                    feePercentage = self.safe_float(currencies[i], 'withdrawalServiceCharge')
                    flatFee = 0
                else:
                    feeType = 'Mixed'
            active = buyEnabled and sellEnabled and depositEnabled and withdrawalEnabled
            result[code] = {
                'id': id,
                'code': code,
                'name': name,
                'active': active,
                # Warning: fee can be both percentage and flat. The `fee` field will have the flat one
                'fee': flatFee,
                'precision': precision,
                'limits': {
                    'amount': {
                        'min': None,
                        'max': None,
                    },
                    'price': {
                        'min': None,
                        'max': None,
                    },
                    'cost': {
                        'min': None,
                        'max': None,
                    },
                    'withdraw': {
                        'min': None,
                        'max': None,
                    },
                },
                'info': currencies[i],
                # custom
                'buyEnabled': buyEnabled,
                'sellEnabled': sellEnabled,
                'depositEnabled': depositEnabled,
                'withdrawalEnabled': withdrawalEnabled,
                'feeType': feeType,  # Fixed | Percentage | Mixed
                'feePercentage': feePercentage,
            }
        return result

    async def fetch_order_book(self, symbol, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        if limit is None:
            limit = 0
        request = {
            'pair': market['id'],
            'limit': limit,
        }
        response = await self.publicGetCmcV1OrderbookPairLimit(self.extend(request, params))
        result = self.safe_value(response, 'data', {})
        return self.parse_order_book(result)

    async def fetch_trades(self, symbol, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        id = market['id']
        request = {
            'pair': id,
        }
        # WARNING: pagination not implemented yet. TODO
        response = await self.publicGetMarketGetTradeHistoryPair(self.extend(request, params))
        result = response['data']
        length = len(result)
        if length <= 0:
            return []
        normalizedTrades = []
        for i in range(0, len(result)):
            normalizedTrades.append(self.normalize_trade_object(result[i], market))
        return self.parse_trades(normalizedTrades, market)

    async def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=100, params={}):
        await self.load_markets()
        market = self.market(symbol)
        pair = market['id']
        quote = pair.split('_')[0]
        base = pair.split('_')[1]
        minutes = self.timeframes[timeframe]
        if minutes is None:
            minutes = 1
        oldSince = since
        if since is None:
            since = self.milliseconds()
        else:
            # recalculate the timestamp. The exchange expects the `until' timestamp instead of since
            since = since + (limit * (minutes * (60 * 1000)))
        request = {
            'baseCurrency': base,
            'quoteCurrency': quote,
            'interval': minutes,
            'timestamp': since,
            'limit': limit,
        }
        response = await self.publicGetMarketGetChartData(self.extend(request, params))
        result = self.safe_value(response, 'data', {})
        # revert since to avoid the check in parseOHLCVs where candles outside the timestamp are removed
        since = oldSince
        return self.parse_ohlcvs(result, market, timeframe, since, limit)

    async def fetch_my_trades(self, symbol=None, since=None, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        request = {
            'side': 'ALL',
            'pair': market['id'],
            'openOrders': False,
            'limit': 20,
            'page': 1,
        }
        if limit is not None:
            request['limit'] = limit
        if params['page'] is not None:
            request['page'] = params['page']
        response = await self.privatePostMyTradeHistory(request)
        trades = response['data']['trades']
        return self.parse_trades(trades, market)

    def normalize_order_object(self, order):
        return {
            'orderId': order['OrderId'],
            'market': order['Market'],
            'trade': order['Trade'],
            'volume': order['Volume'],
            'pendingVolume': order['PendingVolume'],
            'orderStatus': order['Status'],
            'rate': order['Price'],
            'placementDate': order['PlacementDate'],
            'completionDate': order['CompletionDate'],
            'side': order['Side'],
            'type': order['Type'],
        }

    def parse_order(self, order, market=None):
        side = self.safe_string(order, 'side')
        if side is not None:
            side = side.lower()
        type = self.safe_string(order, 'type')
        if type is not None:
            type = type.lower()
        marketCurrency = self.safe_string(order, 'market')
        tradeCurrency = self.safe_string(order, 'trade')
        marketId = marketCurrency + '_' + tradeCurrency
        market = self.markets_by_id[marketId]
        orderStatus = self.safe_value(order, 'orderStatus')
        dateTime = None
        if orderStatus:
            # closed order
            dateTime = self.safe_string(order, 'completionDate')
        else:
            # open order
            dateTime = self.safe_string(order, 'placementDate')
        timestamp = self.parse8601(dateTime)
        amount = self.safe_float(order, 'volume')
        remaining = self.safe_float(order, 'pendingVolume')
        filled = amount - remaining
        price = self.safe_float(order, 'rate')
        cost = price * filled
        symbol = None
        if market is not None:
            symbol = market['symbol']
        status = self.parse_order_status(orderStatus, filled)
        rawTrades = self.safe_value(order, 'mOrders')
        averagePrice = 0
        fee = 0
        trades = []
        if rawTrades is not None and len(rawTrades) != 0:
            for i in range(0, len(rawTrades)):
                tradePrice = self.safe_float(rawTrades[i], 'rate')
                averagePrice += tradePrice
                tradeFee = self.safe_float(rawTrades[i], 'serviceCharge')
                fee += tradeFee
                trades.append(self.parse_trade(rawTrades[i]))
            averagePrice = averagePrice / len(trades)
        id = self.safe_value(order, 'orderId')
        return {
            'id': id,
            'clientOrderId': None,
            'info': order,
            'timestamp': timestamp,
            'datetime': dateTime,
            'lastTradeTimestamp': None,
            'status': status,
            'symbol': symbol,
            'type': type,
            'side': side,
            'price': price,
            'cost': cost,
            'amount': amount,
            'filled': filled,
            'average': averagePrice,
            'remaining': remaining,
            'fee': fee,
            'trades': trades,
        }

    def parse_order_status(self, status, filled):
        orderStatus = None
        if not status:
            orderStatus = 'open'
        elif filled == 0:
            orderStatus = 'canceled'
        else:
            orderStatus = 'closed'
        return orderStatus

    def parse_ohlcv(self, ohlcv, market=None):
        return [
            self.safe_integer(ohlcv, 'time'),
            self.safe_float(ohlcv, 'open'),
            self.safe_float(ohlcv, 'high'),
            self.safe_float(ohlcv, 'low'),
            self.safe_float(ohlcv, 'close'),
            self.safe_float(ohlcv, 'volume'),
        ]

    def normalize_trade_object(self, trade, market=None):
        id = self.safe_value(trade, 'TradeID')
        rate = self.safe_float(trade, 'Rate')
        volume = self.safe_float(trade, 'Volume')
        cost = self.safe_float(trade, 'Total')
        side = self.safe_string(trade, 'Type')
        date = self.safe_string(trade, 'Date')
        s = market['id'].split('_')
        base = s[1]
        quote = s[0]
        return {
            'orderId': str(id),
            'volume': volume,
            'rate': rate,
            'trade': base,
            'market': quote,
            'amount': cost,
            'serviceCharge': None,
            'date': date,
            'side': side.upper(),
        }

    def parse_trade(self, trade, market=None):
        id = self.safe_value(trade, 'orderId')
        rate = self.safe_float(trade, 'rate')
        volume = self.safe_float(trade, 'volume')
        cost = self.safe_float(trade, 'amount')
        side = self.safe_string(trade, 'side')
        date = self.safe_string(trade, 'date')
        fee = self.safe_float(trade, 'serviceCharge')
        baseId = self.safe_string(trade, 'trade')
        quoteId = self.safe_string(trade, 'market')
        marketId = quoteId + '_' + baseId
        symbol = self.markets_by_id[marketId]['symbol']
        timestamp = self.parse8601(date)
        return {
            'id': None,
            'order': id,
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': None,
            'side': side.lower(),
            'takerOrMaker': None,
            'price': rate,
            'amount': volume,
            'cost': cost,
            'fee': fee,
        }

    def parse_tickers(self, rawTickers, market=None):
        tickers = {}
        pairs = list(rawTickers.keys())
        for i in range(0, len(pairs)):
            symbol = self.safe_symbol(pairs[i])
            tickers[symbol] = self.parse_ticker(rawTickers[pairs[i]], pairs[i])
        return tickers

    def parse_ticker(self, ticker, marketId=None):
        timestamp = self.milliseconds()
        symbol = self.safe_symbol(marketId)
        last = self.safe_float(ticker, 'Last')
        return {
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_float(ticker, 'High_24hr'),
            'low': self.safe_float(ticker, 'Low_24hr'),
            'bid': self.safe_float(ticker, 'HeighestBid'),
            'bidVolume': None,
            'ask': self.safe_float(ticker, 'LowestAsk'),
            'askVolume': None,
            'vwap': self.safe_float(ticker, 'weightedAvgPrice'),
            'open': self.safe_float(ticker, 'openPrice'),
            'close': last,
            'last': last,
            'previousClose': None,
            'change': None,
            'percentage': self.safe_float(ticker, 'PercentChange'),
            'average': None,
            'baseVolume': self.safe_float(ticker, 'QuoteVolume'),
            'quoteVolume': self.safe_float(ticker, 'BaseVolume'),
            'info': ticker,
        }

    def get_hmac_from_object(self, data):
        queryString = ''
        keys = list(data.keys())
        keys.sort()
        for i in range(0, len(keys)):
            queryString += keys[i] + '=' + data[keys[i]]
            if i < len(keys) - 1:
                queryString += '&'
        hmac = self.hmac(queryString, self.secret, hashlib.sha512, 'hex')
        hmacString = hmac.upper()
        return hmacString
