<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use \ccxt\ArgumentsRequired;
use \ccxt\BadRequest;
use \ccxt\InvalidOrder;
use \ccxt\OrderNotFound;
use \ccxt\NotSupported;

class youngplatform extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe (), array(
            'id' => 'youngplatform',
            'name' => 'YoungPlatform',
            'countries' => ['IT'],
            'rateLimit' => 2000,
            'certified' => false,
            'pro' => false,
            // new metainfo interface
            'has' => array(
                'fetchClosedOrders' => true,
                'fetchOHLCV' => true,
                'fetchTrades' => true,
                'fetchTime' => 'emulated', // TODO
                'fetchOrderBook' => true,
                'fetchMarkets' => true,
                'fetchTicker' => true,
                'fetchTickers' => true,
                'fetchBalance' => true,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchCurrencies' => true,
                'fetchMyTrades' => true,
                'createOrder' => true,
                'createMarketOrder' => true,
                'cancelOrder' => true,
                'cancelAllOrders' => true,
                'fetchDepositAddress' => true,
                'withdraw' => true,
            ),
            'timeframes' => array(
                '1m' => 1,
                '5m' => 5,
                '15m' => 15,
                '1h' => 60,
                '4h' => 240,
                '1d' => 1440,
                '1w' => 10080,
                '1M' => 43200,
            ),
            'urls' => array(
                'logo' => 'https://exchange.youngplatform.com/61be7df7438ee83abe1fd2e37c7b71bf.svg',
                'test' => array(
                    'public' => 'https://testnode.youngplatform.com',
                    'private' => 'https://testnode.youngplatform.com/order/v2',
                ),
                'api' => array(
                    'public' => 'https://node1.youngplatform.com',
                    'private' => 'https://node1.youngplatform.com/order/v2',
                ),
                'www' => 'https://pro.youngplatform.com',
                'doc' => array(),
                'fees' => 'https://pro.youngplatform.com/fees',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'market/get-market-summary/{pair}',
                        'api/GetSettings',
                        'api/CurrencySettings',
                        'cmc/v1/orderbook/{pair}/{limit}',
                        'market/get-trade-history/{pair}',
                        'market/get-chart-data',
                    ),
                    'put' => array(),
                    'post' => array(),
                    'delete' => array(),
                ),
                'private' => array(
                    'get' => array(),
                    'post' => array(
                        'get-balance',
                        'PlaceOrder',
                        'cancel-my-order',
                        'cancel-all-my-orders',
                        'GenerateAddress',
                        'my-order-history',
                        'my-order-status',
                        'my-trade-history',
                    ),
                    'delete' => array(),
                ),
            ),
            'precisionMode' => TICK_SIZE,
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'taker' => 0.2,
                    'maker' => 0.2,
                ),
            ),
            'commonCurrencies' => array(
                'MCDAI' => 'DAI',
            ),
            // exchange-specific options
            'options' => array(
                // 'fetchTradesMethod' => 'publicGetAggTrades', // publicGetTrades, publicGetHistoricalTrades
                'defaultTimeInForce' => 'GTC', // 'GTC' = Good To Cancel (default), 'IOC' = Immediate Or Cancel
                'recvWindow' => 5 * 1000, // 5 sec
                'timeDifference' => 0, // the difference between system clock and Binance clock
                'adjustForTimeDifference' => false, // controls the adjustment logic upon instantiation
            ),
            // https://binance-docs.github.io/apidocs/spot/en/#error-codes-2
            'exceptions' => array(),
        ));
    }

    public function nonce() {
        return $this->milliseconds() - $this->options['timeDifference'];
    }

    public function fetch_time($params = array ()) {
        return $this->milliseconds();
    }

    public function load_time_difference($params = array ()) {
        $serverTime = $this->fetch_time($params);
        $after = $this->milliseconds();
        $this->options['timeDifference'] = $after - $serverTime;
        return $this->options['timeDifference'];
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        if (!(is_array($this->urls['api']) && array_key_exists($api, $this->urls['api']))) {
            throw new NotSupported($this->id . ' does not have a testnet/sandbox URL for ' . $api . ' endpoints');
        }
        $request = '/' . $this->implode_params($path, $params);
        $query = $this->omit($params, $this->extract_params($path));
        if ($method === 'GET') {
            if ($query) {
                $request .= '?' . $this->urlencode($query);
            }
        }
        if ($api === 'private') {
            if ($params['limit'] !== null) {
                $request .= '?' . $this->urlencode(array( 'limit' => $params['limit'], 'page' => $params['page'] ));
                unset($params['limit']);
                unset($params['page']);
            }
            $this->check_required_credentials();
            $nonce = intval($this->nonce() / 1000);
            $params = array_merge(array( 'timestamp' => $nonce, 'recvWindow' => 5000 ), $params);
            $hmac = $this->get_hmac_from_object($params);
            $body = $this->json($params);
            $headers = array(
                'apiKey' => $this->apiKey,
                'HMAC' => $hmac,
                'Content-Type' => 'application/json',
            );
        }
        $url = $this->urls['api'][$api] . $request;
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function fetch_balance($params = array ()) {
        $currency = $this->safe_string($params, 'currency');
        if ($currency === null) {
            $currency = 'ALL';
        } else {
            $currency = $this->currency_id($currency);
        }
        $params['currency'] = $currency;
        $response = $this->privatePostGetBalance ($params);
        $balances = $this->safe_value($response, 'data', array());
        $result = array( 'info' => $balances );
        for ($i = 0; $i < count($balances); $i++) {
            $currencyId = $this->safe_string($balances[$i], 'currency');
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account();
            $free = $this->safe_float($balances[$i], 'balance');
            $used = $this->safe_float($balances[$i], 'balanceInTrade');
            $total = $free . $used;
            $account['total'] = $total;
            $account['free'] = $free;
            $account['used'] = $used;
            $result[$code] = $account;
        }
        return $this->parse_balance($result);
    }

    public function create_order($symbol, $type, $side, $amount, $price = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $exchangeType = strtoupper($type);
        $exchangeSide = strtoupper($side);
        $baseId = explode('_', $market['id'])[1];
        $quoteId = explode('_', $market['id'])[0];
        $request = array(
            'market' => $quoteId,
            'trade' => $baseId,
            'side' => $exchangeSide,
            'type' => $exchangeType, // MARKET, LIMIT, STOPLIMIT
            'volume' => $this->amount_to_precision($symbol, $amount),
        );
        if ($exchangeType === 'LIMIT') {
            if ($price === null) {
                throw new InvalidOrder($this->id . ' createOrder method requires a $price argument for a ' . $type . ' order');
            }
            $request['rate'] = $this->price_to_precision($symbol, $price);
            $timeInForce = $this->safe_string($params, 'timeInForce');
            if ($timeInForce !== null) {
                if ($timeInForce !== 'GTC' && $timeInForce !== 'IOC' && $timeInForce !== 'FOK') {
                    $request['timeInForce'] = $timeInForce;
                }
            }
        }
        if ($exchangeType === 'STOPLIMIT') {
            $stopPrice = $this->safe_float($params, 'stopPrice');
            if ($price === null) {
                throw new InvalidOrder($this->id . ' createOrder method requires a $price argument for a ' . $type . ' order');
            }
            if ($stopPrice === null) {
                throw new InvalidOrder($this->id . ' createOrder method requires a stop argument for a ' . $type . ' order');
            }
            $request['rate'] = $this->price_to_precision($symbol, $price);
            $request['stop'] = $this->price_to_precision($symbol, $stopPrice);
        }
        if ($exchangeType === 'STOPMARKET') {
            $stopPrice = $this->safe_float($params, 'stopPrice');
            if ($stopPrice === null) {
                throw new InvalidOrder($this->id . ' createOrder method requires a stop argument for a ' . $type . ' order');
            }
            $request['stop'] = $this->price_to_precision($symbol, $stopPrice);
            $request['timeInForce'] = 'GTC';
        }
        if ($exchangeType === 'MARKET') {
            if ($price !== null) {
                throw new InvalidOrder($this->id . ' createOrder method does not support $price argument for a ' . $type . ' order');
            }
        }
        $response = $this->privatePostPlaceOrder ($request);
        //
        //     {
        //         status => 'Success',
        //         data => {
        //             "orderId" => 214083724
        //         }
        //    }
        //
        $timestamp = $this->seconds();
        $result = $this->safe_value($response, 'data');
        $id = $this->safe_integer($result, 'orderId');
        $order = array(
            'id' => $id,
            'info' => $response,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'type' => $type,
            'side' => $side,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'average' => null,
            'filled' => null,
            'remaining' => null,
            'status' => null,
            'fee' => null,
            'trades' => null,
        );
        return $order;
    }

    public function cancel_order($id, $symbol = null, $params = array ()) {
        $this->load_markets();
        $response = null;
        $response = $this->privatePostCancelMyOrder (array_merge(array(
            'orderId' => intval($id),
            'side' => 'ALL',
        ), $params));
        $data = $this->safe_value($response, 'data');
        if ($data === 'Order not found.') {
            throw new OrderNotFound($this->id . ' cancelOrder() error order not found');
        }
        return $response;
    }

    public function cancel_all_orders($symbol = null, $params = array ()) {
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' cancelAllOrders requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
            'side' => 'ALL',
        );
        $response = $this->privatePostCancelAllMyOrders ($request);
        return $response;
    }

    public function fetch_deposit_address($code, $params = array ()) {
        $this->load_markets();
        $currencies = $this->fetch_currencies();
        $currency = $this->safe_value($currencies, $code);
        if ($currency === null) {
            throw BadRequest ($this->id . ' fetchDepositAddress() error invalid currency');
        }
        $request = array(
            'currency' => $currency['id'],
        );
        $separator = strtolower($currency['info']['addressSeparator']);
        $response = $this->privatePostGenerateAddress ($request); // overwrite methods
        $result = $response['data'];
        $address = $this->safe_string($result, 'Address');
        $tag = '';
        if ($separator !== null && $separator !== '') {
            $s = strtolower(explode($separator, $address));
            $tag = $s[1];
            $address = $address->substr (
                0,
                strlen($s[0])
            );
        }
        $this->check_address($address);
        return array(
            'currency' => $code,
            'address' => $address,
            'tag' => $tag,
            'info' => $response,
        );
    }

    public function fetch_open_orders($symbol = null, $since = null, $limit = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'side' => 'ALL',
            'pair' => $market['id'],
            'openOrders' => true,
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        } else {
            $request['limit'] = 20;
        }
        if ($params['page'] !== null) {
            $request['page'] = $params['page'];
        } else {
            $request['page'] = 1;
        }
        $response = $this->privatePostMyOrderHistory ($request);
        $data = $this->safe_value($response, 'data');
        $orders = $this->safe_value($data, 'orders');
        return $this->parse_orders($orders, $market, $since, $limit);
    }

    public function fetch_closed_orders($symbol = null, $since = null, $limit = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'side' => 'ALL',
            'pair' => $market['id'],
            'openOrders' => false,
            'limit' => 20,
            'page' => 1,
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        if ($params['page'] !== null) {
            $request['page'] = $params['page'];
        }
        $response = $this->privatePostMyOrderHistory ($request);
        $data = $this->safe_value($response, 'data');
        $orders = $this->safe_value($data, 'orders');
        return $this->parse_orders($orders, $market, $since, $limit);
    }

    public function fetch_order($id, $symbol = null, $params = array ()) {
        $this->load_markets();
        $request = array(
            'side' => 'ALL',
            'OrderId' => $id,
        );
        $response = $this->privatePostMyOrderStatus ($request);
        $order = $this->safe_value($response, 'data');
        return $this->parse_order($this->normalize_order_object($order));
    }

    public function fetch_markets($params = array ()) {
        $response = $this->publicGetApiGetSettings ();
        if ($this->options['adjustForTimeDifference']) {
            $this->load_time_difference();
        }
        $data = $this->safe_value($response, 'data');
        $res = $this->safe_value($data, 'trade_setting');
        $result = array();
        for ($i = 0; $i < count($res); $i++) {
            $market = $res[$i];
            $baseId = $this->safe_string($market, 'coinName');
            $quoteId = $this->safe_string($market, 'marketName');
            $id = $quoteId . '_' . $baseId;
            $base = $this->safe_currency_code($baseId);
            $quote = $this->safe_currency_code($quoteId);
            $symbol = $base . '/' . $quote;
            $active = $this->safe_value($market, 'tradeEnabled');
            $taker = $this->safe_float($market, 'takerFee');
            $maker = $this->safe_float($market, 'makerFee');
            $lotSize = $this->safe_float($market, 'minTradeAmount');
            $tickSize = $this->safe_float($market, 'minTickSize');
            $minCost = $this->safe_float($market, 'minOrderValue');
            // TODO => precision
            $result[] = array(
                'id' => $id,
                'symbol' => $symbol,
                'base' => $base,
                'quote' => $quote,
                'active' => $active,
                'precision' => array(
                    'amount' => $lotSize,
                    'price' => $tickSize,
                ),
                'taker' => $taker,
                'maker' => $maker,
                'limits' => array(
                    'amount' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'price' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'cost' => array(
                        'min' => $minCost,
                        'max' => null,
                    ),
                ),
                'info' => $market,
            );
        }
        return $result;
    }

    public function fetch_ticker($symbol, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'pair' => $market['id'],
        );
        $response = $this->publicGetMarketGetMarketSummaryPair ($request);
        $ticker = $this->safe_value($response, 'data');
        return $this->parse_ticker($ticker, $market['id']);
    }

    public function fetch_tickers($symbol = null, $params = array ()) {
        $this->load_markets();
        $request = array(
            'pair' => '', // force fetch all $tickers
        );
        $response = $this->publicGetMarketGetMarketSummaryPair ($request);
        $tickers = $this->safe_value($response, 'data');
        return $this->parse_tickers($tickers);
    }

    public function fetch_currencies($params = array ()) {
        $response = $this->publicGetApiCurrencySettings ($params);
        $currencies = $this->safe_value($response, 'data');
        $result = array();
        for ($i = 0; $i < count($currencies); $i++) {
            $id = $this->safe_string($currencies[$i], 'shortName');
            // fees can have both percentage and flat fee
            $code = $this->safe_currency_code($id);
            $name = $this->safe_string($currencies[$i], 'fullName');
            $decimal = $this->safe_integer($currencies[$i], 'decimalPrecision');
            $precision = pow(10, -$decimal);
            // is $active only if all of the below are true
            $buyEnabled = $this->safe_value($currencies[$i], 'tradeEnabled_Buy');
            $sellEnabled = $this->safe_value($currencies[$i], 'tradeEnabled_Sell');
            $depositEnabled = $this->safe_value($currencies[$i], 'depositEnabled');
            $withdrawalEnabled = $this->safe_value($currencies[$i], 'withdrawalEnabled');
            $feeType = $this->safe_string($currencies[$i], 'withdrawalServiceChargeType');
            $flatFee = $this->safe_float($currencies[$i], 'withdrawalServiceCharge');
            $feePercentage = $this->safe_float($currencies[$i], 'withdrawalServiceChargeInBTC');
            if ($feeType === 'Percentage') {
                if ($feePercentage === 0) {
                    $feePercentage = $this->safe_float($currencies[$i], 'withdrawalServiceCharge');
                    $flatFee = 0;
                } else {
                    $feeType = 'Mixed';
                }
            }
            $active = $buyEnabled && $sellEnabled && $depositEnabled && $withdrawalEnabled;
            $result[$code] = array(
                'id' => $id,
                'code' => $code,
                'name' => $name,
                'active' => $active,
                // Warning => fee can be both percentage and flat. The `fee` field will have the flat one
                'fee' => $flatFee,
                'precision' => $precision,
                'limits' => array(
                    'amount' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'price' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'cost' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'withdraw' => array(
                        'min' => null,
                        'max' => null,
                    ),
                ),
                'info' => $currencies[$i],
                // custom
                'buyEnabled' => $buyEnabled,
                'sellEnabled' => $sellEnabled,
                'depositEnabled' => $depositEnabled,
                'withdrawalEnabled' => $withdrawalEnabled,
                'feeType' => $feeType, // Fixed | Percentage | Mixed
                'feePercentage' => $feePercentage,
            );
        }
        return $result;
    }

    public function fetch_order_book($symbol, $limit = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        if ($limit === null) {
            $limit = 0;
        }
        $request = array(
            'pair' => $market['id'],
            'limit' => $limit,
        );
        $response = $this->publicGetCmcV1OrderbookPairLimit (array_merge($request, $params));
        $result = $this->safe_value($response, 'data', array());
        return $this->parse_order_book($result);
    }

    public function fetch_trades($symbol, $limit = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $id = $market['id'];
        $request = array(
            'pair' => $id,
        );
        // WARNING => pagination not implemented yet. TODO
        $response = $this->publicGetMarketGetTradeHistoryPair (array_merge($request, $params));
        $result = $response['data'];
        $length = is_array($result) ? count($result) : 0;
        if ($length <= 0) {
            return array();
        }
        $normalizedTrades = array();
        for ($i = 0; $i < count($result); $i++) {
            $normalizedTrades[] = $this->normalize_trade_object($result[$i], $market);
        }
        return $this->parse_trades($normalizedTrades, $market);
    }

    public function fetch_ohlcv($symbol, $timeframe = '1m', $since = null, $limit = 100, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $pair = $market['id'];
        $quote = explode('_', $pair)[0];
        $base = explode('_', $pair)[1];
        $minutes = $this->timeframes[$timeframe];
        if ($minutes === null) {
            $minutes = 1;
        }
        $oldSince = $since;
        if ($since === null) {
            $since = $this->milliseconds();
        } else {
            // recalculate the timestamp. The exchange expects the `until' timestamp instead of $since
            $since = $since . ($limit * ($minutes * (60 * 1000)));
        }
        $request = array(
            'baseCurrency' => $base,
            'quoteCurrency' => $quote,
            'interval' => $minutes,
            'timestamp' => $since,
            'limit' => $limit,
        );
        $response = $this->publicGetMarketGetChartData (array_merge($request, $params));
        $result = $this->safe_value($response, 'data', array());
        // revert $since to avoid the check in parseOHLCVs where candles outside the timestamp are removed
        $since = $oldSince;
        return $this->parse_ohlcvs($result, $market, $timeframe, $since, $limit);
    }

    public function fetch_my_trades($symbol = null, $since = null, $limit = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'side' => 'ALL',
            'pair' => $market['id'],
            'openOrders' => false,
            'limit' => 20,
            'page' => 1,
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        if ($params['page'] !== null) {
            $request['page'] = $params['page'];
        }
        $response = $this->privatePostMyTradeHistory ($request);
        $trades = $response['data']['trades'];
        return $this->parse_trades($trades, $market);
    }

    public function normalize_order_object($order) {
        return array(
            'orderId' => $order['OrderId'],
            'market' => $order['Market'],
            'trade' => $order['Trade'],
            'volume' => $order['Volume'],
            'pendingVolume' => $order['PendingVolume'],
            'orderStatus' => $order['Status'],
            'rate' => $order['Price'],
            'placementDate' => $order['PlacementDate'],
            'completionDate' => $order['CompletionDate'],
            'side' => $order['Side'],
            'type' => $order['Type'],
        );
    }

    public function parse_order($order, $market = null) {
        $side = $this->safe_string($order, 'side');
        if ($side !== null) {
            $side = strtolower($side);
        }
        $type = $this->safe_string($order, 'type');
        if ($type !== null) {
            $type = strtolower($type);
        }
        $marketCurrency = $this->safe_string($order, 'market');
        $tradeCurrency = $this->safe_string($order, 'trade');
        $marketId = $marketCurrency . '_' . $tradeCurrency;
        $market = $this->markets_by_id[$marketId];
        $orderStatus = $this->safe_value($order, 'orderStatus');
        $dateTime = null;
        if ($orderStatus) {
            // closed $order
            $dateTime = $this->safe_string($order, 'completionDate');
        } else {
            // open $order
            $dateTime = $this->safe_string($order, 'placementDate');
        }
        $timestamp = $this->parse8601($dateTime);
        $amount = $this->safe_float($order, 'volume');
        $remaining = $this->safe_float($order, 'pendingVolume');
        $filled = $amount - $remaining;
        $price = $this->safe_float($order, 'rate');
        $cost = $price * $filled;
        $symbol = null;
        if ($market !== null) {
            $symbol = $market['symbol'];
        }
        $status = $this->parse_order_status($orderStatus, $filled);
        $rawTrades = $this->safe_value($order, 'mOrders');
        $averagePrice = 0;
        $fee = 0;
        $trades = array();
        if ($rawTrades !== null && strlen($rawTrades) !== 0) {
            for ($i = 0; $i < count($rawTrades); $i++) {
                $tradePrice = $this->safe_float($rawTrades[$i], 'rate');
                $averagePrice .= $tradePrice;
                $tradeFee = $this->safe_float($rawTrades[$i], 'serviceCharge');
                $fee .= $tradeFee;
                $trades[] = $this->parse_trade($rawTrades[$i]);
            }
            $averagePrice = $averagePrice / is_array($trades) ? count($trades) : 0;
        }
        $id = $this->safe_value($order, 'orderId');
        return array(
            'id' => $id,
            'clientOrderId' => null,
            'info' => $order,
            'timestamp' => $timestamp,
            'datetime' => $dateTime,
            'lastTradeTimestamp' => null,
            'status' => $status,
            'symbol' => $symbol,
            'type' => $type,
            'side' => $side,
            'price' => $price,
            'cost' => $cost,
            'amount' => $amount,
            'filled' => $filled,
            'average' => $averagePrice,
            'remaining' => $remaining,
            'fee' => $fee,
            'trades' => $trades,
        );
    }

    public function parse_order_status($status, $filled) {
        $orderStatus = null;
        if (!$status) {
            $orderStatus = 'open';
        } else if ($filled === 0) {
            $orderStatus = 'canceled';
        } else {
            $orderStatus = 'closed';
        }
        return $orderStatus;
    }

    public function parse_ohlcv($ohlcv, $market = null) {
        return array(
            $this->safe_integer($ohlcv, 'time'),
            $this->safe_float($ohlcv, 'open'),
            $this->safe_float($ohlcv, 'high'),
            $this->safe_float($ohlcv, 'low'),
            $this->safe_float($ohlcv, 'close'),
            $this->safe_float($ohlcv, 'volume'),
        );
    }

    public function normalize_trade_object($trade, $market = null) {
        $id = $this->safe_value($trade, 'TradeID');
        $rate = $this->safe_float($trade, 'Rate');
        $volume = $this->safe_float($trade, 'Volume');
        $cost = $this->safe_float($trade, 'Total');
        $side = $this->safe_string($trade, 'Type');
        $date = $this->safe_string($trade, 'Date');
        $s = explode('_', $market['id']);
        $base = $s[1];
        $quote = $s[0];
        return array(
            'orderId' => (string) $id,
            'volume' => $volume,
            'rate' => $rate,
            'trade' => $base,
            'market' => $quote,
            'amount' => $cost,
            'serviceCharge' => null,
            'date' => $date,
            'side' => strtoupper($side),
        );
    }

    public function parse_trade($trade, $market = null) {
        $id = $this->safe_value($trade, 'orderId');
        $rate = $this->safe_float($trade, 'rate');
        $volume = $this->safe_float($trade, 'volume');
        $cost = $this->safe_float($trade, 'amount');
        $side = $this->safe_string($trade, 'side');
        $date = $this->safe_string($trade, 'date');
        $fee = $this->safe_float($trade, 'serviceCharge');
        $baseId = $this->safe_string($trade, 'trade');
        $quoteId = $this->safe_string($trade, 'market');
        $marketId = $quoteId . '_' . $baseId;
        $symbol = $this->markets_by_id[$marketId]['symbol'];
        $timestamp = $this->parse8601($date);
        return array(
            'id' => null,
            'order' => $id,
            'info' => $trade,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'type' => null,
            'side' => strtolower($side),
            'takerOrMaker' => null,
            'price' => $rate,
            'amount' => $volume,
            'cost' => $cost,
            'fee' => $fee,
        );
    }

    public function parse_tickers($rawTickers, $market = null) {
        $tickers = array();
        $pairs = is_array($rawTickers) ? array_keys($rawTickers) : array();
        for ($i = 0; $i < count($pairs); $i++) {
            $symbol = $this->safe_symbol($pairs[$i]);
            $tickers[$symbol] = $this->parse_ticker($rawTickers[$pairs[$i]], $pairs[$i]);
        }
        return $tickers;
    }

    public function parse_ticker($ticker, $marketId = null) {
        $timestamp = $this->milliseconds();
        $symbol = $this->safe_symbol($marketId);
        $last = $this->safe_float($ticker, 'Last');
        return array(
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $this->safe_float($ticker, 'High_24hr'),
            'low' => $this->safe_float($ticker, 'Low_24hr'),
            'bid' => $this->safe_float($ticker, 'HeighestBid'),
            'bidVolume' => null,
            'ask' => $this->safe_float($ticker, 'LowestAsk'),
            'askVolume' => null,
            'vwap' => $this->safe_float($ticker, 'weightedAvgPrice'),
            'open' => $this->safe_float($ticker, 'openPrice'),
            'close' => $last,
            'last' => $last,
            'previousClose' => null,
            'change' => null,
            'percentage' => $this->safe_float($ticker, 'PercentChange'),
            'average' => null,
            'baseVolume' => $this->safe_float($ticker, 'QuoteVolume'),
            'quoteVolume' => $this->safe_float($ticker, 'BaseVolume'),
            'info' => $ticker,
        );
    }

    public function get_hmac_from_object($data) {
        $queryString = '';
        $keys = is_array($data) ? array_keys($data) : array();
        $keys->sort ();
        for ($i = 0; $i < count($keys); $i++) {
            $queryString .= $keys[$i] . '=' . $data[$keys[$i]];
            if ($i < strlen($keys) - 1) {
                $queryString .= '&';
            }
        }
        $hmac = $this->hmac($queryString, $this->secret, 'sha512', 'hex');
        $hmacString = strtoupper($hmac);
        return $hmacString;
    }
}
